version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - mariadb_data:/var/lib/mysql


  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile

    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:${MYSQL_PORT}/${MYSQL_DATABASE}?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - mariadb
    links:
      - mariadb

volumes:
  mariadb_data:
